#!/bin/bash

echo "Waiting for service -- ${VAULT_ADDR}/v1/sys/init (Sleeping 2s) ..."
while ! curl -s -k -I -m 5 "${VAULT_ADDR}/v1/sys/ini" | grep 'HTTP/1.1 '; do echo "Waiting for service -- ${VAULT_ADDR}/v1/sys/init (Sleeping 2s) ..."; sleep 2; done

echo "Service is up"
IS_INITIALIZED="$(curl -k -s -m 5 "${VAULT_ADDR}/v1/sys/ini" | jq '.initialized')"
if [ "$IS_INITIALIZED" != 'true' ]; then
  echo 'Initializing vault'
  /app/vault/bin/vault init -address=${VAULT_ADDR} | tee /tmp/vault.init.keys
else
  echo 'Vault is already initialized'
fi

echo 'Finished vault-init'
